-- STANDARDIZE TEXT FIELDS
-- 11 ROWS AFFECTED FOR COMPANY COLUMN

# SELECT AND VIEW ALL ROWS
SELECT *
FROM portfolio_table;

# SELECT DISTINCT COMPANIES
SELECT DISTINCT company
FROM portfolio_table
LIMIT 3000;

# VIEW COMPANIES BEFORE AND AFTER TRIMMING UNWANTED CHARACTERS
SELECT company, TRIM(company)
FROM portfolio_table
LIMIT 3000;

# TRIM LEADING AND TRAILING SPACES IN COMPANY COLUMN
UPDATE portfolio_table
SET company = TRIM(company);
SELECT *
FROM portfolio_table;

SELECT industry
FROM portfolio_table
WHERE industry LIKE '%-%';

# SELECT ROWS HAVING HYPHEN IN INDUSTRY
SELECT *
FROM portfolio_table
WHERE industry LIKE '%-%';

# SELECT ROWS HAVING CHARACTERS OTHER THAN ALPHABETS AND SPACES IN INDUSTRY
SELECT *
FROM portfolio_table
WHERE industry REGEXP '[^A-Za-z ]';

# SELECT ROWS HAVING CHARACTERS OTHER THAN ALPHABETS AND SPACES IN LOCATION
SELECT *
FROM portfolio_table
WHERE location REGEXP '[^A-Za_z -]';

# SELECT ROWS HAVING CHARACTERS OTHER THAN DECIMALS AND POINTS IN `percentage_laid_off`
SELECT *
FROM portfolio_table
WHERE percentage_laid_off REGEXP '[^0-9 .]';

# SELECT ROWS HAVING CHARACTERS OTHER THAN NUMBERS AND SLASH IN DATE
SELECT *
FROM portfolio_table 
WHERE `date` REGEXP '[^0-9/]';

# SELECT ONLY ROWS HAVING CHARACTERS OTHER THAN ALPHABETS AND SPACES IN STAGE COLUMN
SELECT *
FROM portfolio_table
WHERE stage REGEXP '[^A-Za-z ]';

# SELECT ROWS THAT HAVE CHARACTERS OTHER THAN ALPHABETS AND SPACE IN COUNTRY COLUMN_4 ROWS RETURNED
SELECT *
FROM portfolio_table
WHERE country REGEXP '[^A-Za-z ]';

# REMOVE TRAILING FULLSTOP FROM COUNTRY COLUMN_4 ROWS AFFECTED 
UPDATE portfolio_table
SET country = TRIM(TRAILING '.' FROM country );

SELECT *
FROM portfolio_table
WHERE funds_raised_millions REGEXP '[^0-9]'
LIMIT 3000;
SELECT DISTINCT funds_raised_millions
FROM portfolio_table;

# SELECT AND VIEW VALUES WITH OTHER CHARACTERS THAN NUMBERS IN 'funds_raised_millions' COLUMN
SELECT *
FROM portfolio_table
WHERE funds_raised_millions NOT REGEXP '^[0-9]+$' 
ORDER BY funds_raised_millions;
# TRIM LEADING AND TRAILING CHARACTERS 